name: Continuous Integration

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]

  # push:
    # Run on pushes to feature branches?
    # branches: [ "master" ]

  # Allow manual execution on the website
  workflow_dispatch:

  # Also reusable for Deliver Workflow
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  workflow_call:


jobs:
  
  powershell:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v3

      # https://docs.github.com/en/actions/learn-github-actions/variables
      - name: Echo GitHub Variables
        run: |
          echo "GITHUB_BASE_REF = $env:GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF = $env:GITHUB_HEAD_REF"
          echo "GITHUB_JOB = $env:GITHUB_JOB"
          echo "GITHUB_REF = $env:GITHUB_REF"
          echo "GITHUB_REF_NAME = $env:GITHUB_REF_NAME"
          echo "GITHUB_REF_TYPE = $env:GITHUB_REF_TYPE"
          echo "GITHUB_RUN_ATTEMPT = $env:GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID = $env:GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER = $env:GITHUB_RUN_NUMBER"

      - name: Test
        run: .\build\TestPowerShell.ps1

      - name: Package
        run: .\build\PackagePowerShell.ps1
      
      # Upload artifact so Deliver Workflow can download and publish it
      - name: Upload Package Artifact
        uses: actions/upload-artifact@v3
        with:
          name: powershell-package
          path: PowerShell/bin/*.nupkg

  
  terraform:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Echo GitHub Variables
      run: |
        echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
        echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
        echo "GITHUB_JOB = $GITHUB_JOB"
        echo "GITHUB_REF = $GITHUB_REF"
        echo "GITHUB_REF_NAME = $GITHUB_REF_NAME"
        echo "GITHUB_REF_TYPE = $GITHUB_REF_TYPE"
        echo "GITHUB_RUN_ATTEMPT = $GITHUB_RUN_ATTEMPT"
        echo "GITHUB_RUN_ID = $GITHUB_RUN_ID"
        echo "GITHUB_RUN_NUMBER = $GITHUB_RUN_NUMBER"

    # https://github.com/marketplace/actions/hashicorp-setup-terraform
    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: latest

    - name: Terraform version
      run: terraform -version

    - name: Terraform init
      run: terraform init -no-color

    - name: Terraform fmt
      run: terraform fmt -check -recursive    

    - name: Terraform validate
      run: terraform validate -no-color
