name: Deliver

on:
  push:
    branches: [ "master" ]
  
  # Allow manual execution on the website
  # Can be used to publish pre-release packages for PRs and feature branches
  workflow_dispatch:


jobs:

  # Run the CI Workflow so we don't have to duplicate it in this file
  # https://docs.github.com/en/actions/using-workflows/reusing-workflows
  CI:
    uses: ./.github/workflows/ci.yml
  
  powershell:
    runs-on: windows-2022
    
    # Needs CI to pass before delivering
    # https://docs.github.com/en/actions/using-jobs/using-jobs-in-a-workflow#defining-prerequisite-jobs
    needs: CI
    
    steps:
      - name: Echo GitHub Variables
        run: |
          echo "GITHUB_BASE_REF = $env:GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF = $env:GITHUB_HEAD_REF"
          echo "GITHUB_JOB = $env:GITHUB_JOB"
          echo "GITHUB_REF = $env:GITHUB_REF"
          echo "GITHUB_REF_NAME = $env:GITHUB_REF_NAME"
          echo "GITHUB_REF_TYPE = $env:GITHUB_REF_TYPE"
          echo "GITHUB_RUN_ATTEMPT = $env:GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID = $env:GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER = $env:GITHUB_RUN_NUMBER"
    
      # Download PowerShell package from CI Workflow for publishing
      # https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts
      - name: Download Package Artifact
        uses: actions/download-artifact@v3
        with:
          name: powershell-package
      
      - name: Deliver
        env:
          deliver_secret: ${{ secrets.NOT_SECURE_TEST_SECRET }}
        run: |
          echo "Test step for delivering PowerShell module"
          echo "NOT_SECURE_TEST_SECRET: $deliver_secret"
          Get-ChildItem -Filter '*.nupkg'"
          echo "Delivery Done!"
