name: PowerShell

on:
  pull_request:
    types: [assigned, opened, edited, synchronize, reopened]

  push:
    # Run on pushes to feature branches?
    # branches: [ "master" ]
    branches: [ "*" ]
    tags: [ "[1-9].[0-9]+.[0-9]+" ]

  # Allow manual execution on the website
  workflow_dispatch:
    inputs:
      force_delivery:
        description: 'Force delivery of the PowerShell module package'
        default: false
        required: true
        type: boolean


jobs:
  powershell:
    # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
    # https://github.com/actions/runner-images/blob/main/images/win/Windows2022-Readme.md
    runs-on: windows-2022
    steps:

      - uses: actions/checkout@v4

      # https://docs.github.com/en/actions/learn-github-actions/variables
      - name: Echo GitHub Variables
        run: |
          echo "GITHUB_BASE_REF = $env:GITHUB_BASE_REF"
          echo "GITHUB_EVENT_NAME = $env:GITHUB_EVENT_NAME"
          echo "GITHUB_HEAD_REF = $env:GITHUB_HEAD_REF"
          echo "GITHUB_JOB = $env:GITHUB_JOB"
          echo "GITHUB_REF = $env:GITHUB_REF"
          echo "GITHUB_REF_NAME = $env:GITHUB_REF_NAME"
          echo "GITHUB_REF_TYPE = $env:GITHUB_REF_TYPE"
          echo "GITHUB_RUN_ATTEMPT = $env:GITHUB_RUN_ATTEMPT"
          echo "GITHUB_RUN_ID = $env:GITHUB_RUN_ID"
          echo "GITHUB_RUN_NUMBER = $env:GITHUB_RUN_NUMBER"

      - name: Test
        run: .\build\TestPowerShell.ps1

      - name: Package
        run: .\build\PackagePowerShell.ps1
      
      - name: Deliver
        # https://docs.github.com/en/actions/learn-github-actions/contexts#inputs-context
        # https://docs.github.com/en/actions/learn-github-actions/contexts#github-context
        # Deliver when:
        #   Checking the force_delivery option during a manual execution
        #   Pushing to master
        #   Pushing a tag
        if: |
              inputs.force_delivery || 
              ( github.event_name	== 'push' && github.ref_name == 'master' ) || 
              ( github.event_name	== 'push' && github.ref_type == 'tag' )
        env:
          deliver_secret: ${{ secrets.NOT_SECURE_TEST_SECRET }}
        run: |
          echo "Test step for delivering PowerShell module"
          echo "inputs force_delivery: ${{ inputs.force_delivery }}"
          echo "env deliver_secret: $env:deliver_secret"
          echo "secrets NOT_SECURE_TEST_SECRET: ${{ secrets.NOT_SECURE_TEST_SECRET }}"
          Get-ChildItem -Path '.\PowerShell\bin' -Filter '*.nupkg'
          echo "Delivery Done!"
